version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: Aa123456
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: bookstore
            MYSQL_PASSWORD: book123
        networks:
            - mynet
        volumes:
          - mysqlvolume:/var/li/mysql
    myapp:
        image: "mecit35/flask_mysql"
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - mynet

networks:
    mynet:
        driver: bridge
volumes:
  mysqlvolume: